### PR TITLE
More informative err msg in _from_parse_feature()

### PR DESCRIPTION
**Pull request by terrytangyuan**

### CODE REVIEW

**Comment by terrytangyuan** [comment]
BTW, would you guys be able to share some roadmap for this project? This way it's easier for other people to contribute. We might be interested in making this project available in R if you are interested in collaborating.

**Comment by KesterTong** [comment]
Thanks very much for this contribution.  @davidsoergel could you review this?

To clarify our process for accepting external requests, in general we will first apply the change internally and then close or merge the PR.  This is because our internal repo is the source-of-truth so we need to first make the changes in the internal repo.

Regarding future plans, tf.Transform is being actively developed but we don't have an official roadmap.  However please feel free to open issues to either request features, or outline changes that you would like to contribute yourself.  In the case of R integration, could you open an issue and briefly outline what your plan is and what changes would be needed to tf.Transform code?

**Comment by davidsoergel** [comment]
Thanks for this!  The change looks good to me, so I'm applying it internally.  That will make it show up here in a future push.

**Comment by davidsoergel** [comment]
On further discussion we think it's OK to merge here directly.  Thanks!

**Pull request merged**
