### PR TITLE
Fix division by 0 in scale_to_z_score

### PR DESCRIPTION
**Pull request by Debasish-Das-CK**
1. Added vectorization support for zscore
2. Added test impl_test.testScaleToZScoreVectorized
3. Ran unit test as: python -m unittest -q tensorflow_transform.beam.impl_test
4. Fixes #47

### CODE REVIEW

**Comment by Debasish-Das-CK** [comment]
I signed it

**Comment by puneith** [comment]
@Debasish-Das-CK I am checking internally in the system and the CLA is not signed. Are your commits coming from debasish.das@creditkarma.com email address? Can you please confirm the CLA or retry.

**Comment by Debasish-Das-CK** [comment]
Yes...commits are from debasish.das@creditkarma.com...I will confirm from our legal next week...we did send it out last week...

**Comment by debasish83** [comment]
We signed the CLA today....can you please recheck?

**Comment by debasish83** [comment]
I signed it!

**Comment by zoyahav** [comment]
@debasish83 / @Debasish-Das-CK I'm seeing that both the email address debasish.das@creditkarma.com and github user @debasish83 have signed the CLA (separately), but the github user @Debasish-Das-CK hasn't.
Perhaps it was created with a different email?

**Comment by Debasish-Das-CK** [comment]
@zoyahav @debasish83 is my personal contributions @Debasish-Das-CK has debasish.das@creditkarma.com associated with it which is my work github account...

**Comment by puneith** [comment]
@Debasish-Das-CK You have CLA signed with debasish.das@creditkarma.com / debasish83 so make sure you amend your commits with correct email.

**Comment by Debasish-Das-CK** [comment]
@PedroRegueiro can you please give consent ? I am trying to close #47 as well...

**Comment by Debasish-Das-CK** [comment]
@puneith my commit logs has the correct email address...I made it visible and looks like the issue is resolved now:
commit d77ad3d04ca134393abc6674d74ec713a1c84f3a (HEAD -> zscore, origin/zscore)
Author: Debasish Das <debasish.das@creditkarma.com>
Date:   Sat Jun 9 12:18:37 2018 -0700
feature vectorization for zscore

**Comment by PedroRegueiro** [comment]
Yeah, I'm OK with my commits being contributed on this PR... I'll close #47.

**Comment by Debasish-Das-CK** [comment]
@zoyahav I will take care of review comments...I am apart from that rest of the CLA issues are now sorted out...

**Comment by zoyahav** [comment]
@Debasish-Das-CK, note we will most likely release the next version this week, so we would need to get this PR merged soon to include it.
Otherwise this will have to wait for the next one.

**Pull request merged**
